version: 2.1
orbs:
  k8s: digitalocean/k8s@0.1.1
  doctl: digitalocean/cli@0.1.1
  helm: circleci/helm@3.0.0
jobs:
  build:
    docker:
      - image: cimg/base:2023.09
    steps:
      - checkout
      - setup_remote_docker
      - doctl/install
      - k8s/install
      - doctl/initialize:
          digitalocean-access-token: DIGITALOCEAN_ACCESS_TOKEN
      - run:
          name: Save Kubernetes Config
          command: |
            doctl kubernetes cluster kubeconfig save ${CLUSTER_NAME}
      - run:
          name: Your Kubernetes Commands
          command: |
            kubectl get pods
            # Add more Kubernetes commands as needed
      - helm/install_helm_chart:
          add-repo: ./kube-prometheus-stack/
          chart: kube-prometheus-stack

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
