version: 2.1
orbs:
  k8s: digitalocean/k8s@0.1.1
  kubernetes: circleci/kubernetes@1.3.0
jobs:
  build:
    executor: kubernetes/default
    steps:
      - k8s/install
      - doctl/initialize:
          digitalocean-access-token: DIGITALOCEAN_ACCESS_TOKEN
      - run: |
          doctl kubernetes cluster kubeconfig save do-k8s-practice
      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
